### ISSUE TITLE
API Question/issue: How to close connection?

### ISSUE THREAD

**Issue by TE-JoakimElvander** [thejinchao/turbolink#15]
Hi, 
Thanks again for a great plugin!
I'm struggling to find a proper way to close the connection in the APIs though after a stream is finished.
I've tried doing pClient->Shutdown() and assigning a nullptr to the pClient (pClient of course being the client received through the MakeClient call on the service). But I still get GOAWAY messages in the log after the stream is finished.
Here's an excerpt from the log showing the messages I get.

`LogMYAPP: UgRPCDownloader::OnLiveStreamServiceContextChanged: State changed to Done. Closing connection.
LogTurboLink: Destruct GrpcClient
LogTurboLink: grpc:(E:\TurboLink\turbolink-libraries\Source\grpc\grpc-1.41.0\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1100)@xW:: Got goaway [11] err={"created":"@1685449280.543000000","description":"GOAWAY received","file":"E:\TurboLink\turbolink-libraries\Source\grpc\grpc-1.41.0\src\core\ext\transport\chttp2\transport\chttp2_transport.c
c","file_line":1089,"grpc_status":14,"http2_error":11,"raw_bytes":"too_many_pings"}
LogTurboLink: Error: grpc:(E:\TurboLink\turbolink-libraries\Source\grpc\grpc-1.41.0\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1111)Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
LogMYAPP: UgRPCDownloader::OnLiveStreamServiceStateChanged: State changed to Idle.`

Is the closing down of connections a missing feature, or have I missed something?

**Comment by TE-JoakimElvander** [comment]
hmm...just found the ReleaseService function in the TurboLinkManager... maybe that was what I needed...? :)

**Comment by thejinchao** [comment]
Yes, calling `UTurboLinkGrpcManager::ReleaseService` will attempt to release the service and close the network connection.
But this process is not executed immediately. After calling `ReleaseService`, if the service is no longer used elsewhere, it will be set to `PendingShutdown` state, and this state will remain for 60 seconds. If there is no new use of this service within 60 seconds, the service will actually be closed. The closing of the socket link is more complicated, because grpc uses `Channel` to save the socket link with the grpc service, and there may be multiple different services sharing a channel. Only after all the services using this channel are closed, The channel will be destroyed and the socket connection will be closed.
But in most cases you don't need to care about these, just call that function。

**Comment by TE-JoakimElvander** [comment]
Thanks for the answer. I guess the "bug" then is that maybe this should be mentioned in the README.md file how the proper procedure is for the closing or restart of services?

**Comment by thejinchao** [comment]
No problem, I'll update the docs when I have time. You can download another [example project](https://drive.google.com/file/d/1W8dx-BAlzZnDy-_2tA1GXJAcjlIyYcak/view?usp=sharing), which contains the code on how to close the service
