### ISSUE TITLE
hyphen in proto file name isn't supported.

### ISSUE THREAD

**Issue by 6r0m** [thejinchao/turbolink#18]
1) generate-code.cmd
2) add generated files and rebuild solution
3) build full demo project, errors:
  test-statusMessage.generated.h(12): [C4067] unexpected tokens following preprocessor directive - expected a newline
  test-statusMessage.generated.h(15): [C2008] '-': unexpected in macro definition
  test-statusMessage.generated.h(12): [C4067] unexpected tokens following preprocessor directive - expected a newline
  test-statusMessage.generated.h(15): [C2008] '-': unexpected in macro definition

**Comment by thejinchao** [comment]
Very interesting, I think it should be because the source file name of the UE project should follow specific rules, such as camel case, cannot contain spaces and hyphen. I can do some conversions when generating these files, such as converting hyphen to underscores, but I still suggest that you should not include hyphen signs in your proto file name.

**Comment by thejinchao** [comment]
fixed in the latest version
