### ISSUE TITLE
gRPC server support?

### ISSUE THREAD

**Issue by swiftysix** [thejinchao/turbolink#8]
Hi,

You're plugin looks very nice. However, I need a gRPC server in Unreal Engine. From the description it looks like this plugin only supports client side in UE. Is that correct?

- Is it planned to also support gRPC server in the plugin?
- Since you've written the plugin yourself, what's your estimate how hard would it be to modify the plugin to also add in a server? I'm considering doing this myself at the moment. Are there any major roadblocks you can think of?

**Comment by thejinchao** [comment]
Yes, this plugin currently only supports client-side functionality, and I have no plans to support server-side functionality.
According to my experience, to support the grpc server function in UE, the first thing to solve is the cross-platform problem. In order to realize the grpc client function on multiple platforms (including windows, android, ios and ps5), I modified the code of `grpc` and several other open source libraries (`abseil`, `protobuf` and `re2`) it depends on. The code involves io, network and multi-threading, especially ps5, it is very troublesome to debug. If server functions are to be implemented, I believe more code may need to be modified.
The second difficulty I think should be the need to implement a reasonable multi-threaded task processing mechanism. Because as a grpc server, it is obviously necessary to handle multiple task requests. In this case, you need to implement a multi-thread pool and also need to cooperate with the main thread of UE (such as blueprints). I think this will be a very complicated thing.

**Comment by WilSimpson** [comment]
I would also question why you would want to do this. I can't think of any use-case where having the gRPC server in the UE process would be better or even a good option. What use case are you looking at?

**Comment by swiftysix** [comment]
@thejinchao Oh, I didn't realize that this plugin supports all these platform. The project I'm working on is more of a proof of concept for my employer, so platform compatibility is not of great concern for now. It's also non-gamedev so PS5 would probably not be in scope.
The threading issue is a bigger problem I guess. I'd only need connect one or a couple of clients, so I guess the problem is also not that hard compared to a server which needs to support thousands of connections. Still, you might be right and hacking something myself might be out of my reach for now.

**Comment by WilSimpson** [comment]
@swiftysix Here are some quick thoughts:
1. If you're the developer of the 3d application, make that application the gRPC server. 
1. If the host (or only client) is on the same computer as the desktop app: write the data points to a file and read from that file in unreal. Aka memory-mapped file.
1. Make a sidecar/proxy gRPC server. Have two endpoints: one which accepts a data point input stream and saves it in memory queue (desktop app inputs). Have another endpoint that reads from the queue and outputs (game client reads). If you need lower latency between the exchange of data you could do something like go channels.

As an aside multi-threading shouldn't be an obstacle. Create a runnable thread for each stream unreal is taking. If it's multiplayer, then only the dedicated server (or host) receives the data from the application and let unreal handle networking to the connected players.

I don't think 2 is the best option.

**Comment by thejinchao** [comment]
Since your server (unreal engine program) runs on some single operating system and does not need to consider cross-platform, and the number of clients is small, then I think it is still possible to implement the grpc server in UE. My suggestion is not to consider blueprints, try to implement all operations with grpc in c++, and minimize the coupling between server logic and grpc library。
